/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AppV1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "createServerMessage"
      | "getPaywallStatus"
      | "initialize"
      | "setAccountStatus"
      | "setContractStatus"
      | "setInvoiceExpiration"
      | "setRole"
      | "setTokenStatus"
      | "unlockPaywall"
      | "upgrade"
      | "version"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EffectivelyTransfer"
      | "Initialized"
      | "SetAccountStatus"
      | "SetContractStatus"
      | "SetHandlingFeeRatio"
      | "SetInvoiceExpiration"
      | "SetRole"
      | "SetTokenStatus"
      | "UnlockPaywall"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createServerMessage",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaywallStatus",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAccountStatus",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setContractStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setInvoiceExpiration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRole",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenStatus",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockPaywall",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "upgrade", values?: undefined): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createServerMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaywallStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAccountStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContractStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInvoiceExpiration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTokenStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockPaywall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace EffectivelyTransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    from: string;
    to: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetAccountStatusEvent {
  export type InputTuple = [
    account: AddressLike,
    previousStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    previousStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    account: string;
    previousStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetContractStatusEvent {
  export type InputTuple = [
    previousStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [previousStatus: bigint, newStatus: bigint];
  export interface OutputObject {
    previousStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetHandlingFeeRatioEvent {
  export type InputTuple = [
    previousHandlingFeeRatio: BigNumberish,
    newHandlingFeeRatio: BigNumberish
  ];
  export type OutputTuple = [
    previousHandlingFeeRatio: bigint,
    newHandlingFeeRatio: bigint
  ];
  export interface OutputObject {
    previousHandlingFeeRatio: bigint;
    newHandlingFeeRatio: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetInvoiceExpirationEvent {
  export type InputTuple = [
    previousExpiration: BigNumberish,
    newExpiration: BigNumberish
  ];
  export type OutputTuple = [previousExpiration: bigint, newExpiration: bigint];
  export interface OutputObject {
    previousExpiration: bigint;
    newExpiration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetRoleEvent {
  export type InputTuple = [
    account: AddressLike,
    previousRole: BigNumberish,
    newRole: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    previousRole: bigint,
    newRole: bigint
  ];
  export interface OutputObject {
    account: string;
    previousRole: bigint;
    newRole: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetTokenStatusEvent {
  export type InputTuple = [
    token: AddressLike,
    previousStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    previousStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    token: string;
    previousStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnlockPaywallEvent {
  export type InputTuple = [
    account: AddressLike,
    signer: AddressLike,
    postID: BigNumberish,
    consumer: AddressLike
  ];
  export type OutputTuple = [
    account: string,
    signer: string,
    postID: bigint,
    consumer: string
  ];
  export interface OutputObject {
    account: string;
    signer: string;
    postID: bigint;
    consumer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AppV1 extends BaseContract {
  connect(runner?: ContractRunner | null): AppV1;
  waitForDeployment(): Promise<this>;

  interface: AppV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createServerMessage: TypedContractMethod<
    [
      seller: AddressLike,
      consumer: AddressLike,
      invoiceID: BigNumberish,
      postID: BigNumberish,
      paymentToken: AddressLike,
      paymentAmount: BigNumberish,
      consumerSignatureVersion: BigNumberish,
      affiliate: AddressLike,
      affiliateRatio: BigNumberish
    ],
    [string],
    "view"
  >;

  getPaywallStatus: TypedContractMethod<
    [signer: AddressLike, postID: BigNumberish, consumer: AddressLike],
    [
      [boolean, bigint, bigint] & {
        isUnlocked: boolean;
        invoiceID: bigint;
        unlockedBlockNumber: bigint;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [initialAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  setAccountStatus: TypedContractMethod<
    [account: AddressLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  setContractStatus: TypedContractMethod<
    [status: BigNumberish],
    [void],
    "nonpayable"
  >;

  setInvoiceExpiration: TypedContractMethod<
    [expiration: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRole: TypedContractMethod<
    [account: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenStatus: TypedContractMethod<
    [token: AddressLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  unlockPaywall: TypedContractMethod<
    [
      serverSignature: BytesLike,
      sellerTermsMessageHash: BytesLike,
      sellerTermsSignature: BytesLike,
      consumerSignatureVersion: BigNumberish,
      affiliateTermsMessageHash: BytesLike,
      affiliateTermsSignature: BytesLike,
      invoiceID: BigNumberish,
      postID: BigNumberish,
      paymentToken: AddressLike,
      paymentAmount: BigNumberish,
      affiliateRatio: BigNumberish
    ],
    [void],
    "payable"
  >;

  upgrade: TypedContractMethod<[], [void], "nonpayable">;

  version: TypedContractMethod<[], [bigint], "view">;

  withdraw: TypedContractMethod<
    [to: AddressLike, contractAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createServerMessage"
  ): TypedContractMethod<
    [
      seller: AddressLike,
      consumer: AddressLike,
      invoiceID: BigNumberish,
      postID: BigNumberish,
      paymentToken: AddressLike,
      paymentAmount: BigNumberish,
      consumerSignatureVersion: BigNumberish,
      affiliate: AddressLike,
      affiliateRatio: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPaywallStatus"
  ): TypedContractMethod<
    [signer: AddressLike, postID: BigNumberish, consumer: AddressLike],
    [
      [boolean, bigint, bigint] & {
        isUnlocked: boolean;
        invoiceID: bigint;
        unlockedBlockNumber: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[initialAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAccountStatus"
  ): TypedContractMethod<
    [account: AddressLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setContractStatus"
  ): TypedContractMethod<[status: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setInvoiceExpiration"
  ): TypedContractMethod<[expiration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRole"
  ): TypedContractMethod<
    [account: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenStatus"
  ): TypedContractMethod<
    [token: AddressLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unlockPaywall"
  ): TypedContractMethod<
    [
      serverSignature: BytesLike,
      sellerTermsMessageHash: BytesLike,
      sellerTermsSignature: BytesLike,
      consumerSignatureVersion: BigNumberish,
      affiliateTermsMessageHash: BytesLike,
      affiliateTermsSignature: BytesLike,
      invoiceID: BigNumberish,
      postID: BigNumberish,
      paymentToken: AddressLike,
      paymentAmount: BigNumberish,
      affiliateRatio: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "upgrade"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [to: AddressLike, contractAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EffectivelyTransfer"
  ): TypedContractEvent<
    EffectivelyTransferEvent.InputTuple,
    EffectivelyTransferEvent.OutputTuple,
    EffectivelyTransferEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "SetAccountStatus"
  ): TypedContractEvent<
    SetAccountStatusEvent.InputTuple,
    SetAccountStatusEvent.OutputTuple,
    SetAccountStatusEvent.OutputObject
  >;
  getEvent(
    key: "SetContractStatus"
  ): TypedContractEvent<
    SetContractStatusEvent.InputTuple,
    SetContractStatusEvent.OutputTuple,
    SetContractStatusEvent.OutputObject
  >;
  getEvent(
    key: "SetHandlingFeeRatio"
  ): TypedContractEvent<
    SetHandlingFeeRatioEvent.InputTuple,
    SetHandlingFeeRatioEvent.OutputTuple,
    SetHandlingFeeRatioEvent.OutputObject
  >;
  getEvent(
    key: "SetInvoiceExpiration"
  ): TypedContractEvent<
    SetInvoiceExpirationEvent.InputTuple,
    SetInvoiceExpirationEvent.OutputTuple,
    SetInvoiceExpirationEvent.OutputObject
  >;
  getEvent(
    key: "SetRole"
  ): TypedContractEvent<
    SetRoleEvent.InputTuple,
    SetRoleEvent.OutputTuple,
    SetRoleEvent.OutputObject
  >;
  getEvent(
    key: "SetTokenStatus"
  ): TypedContractEvent<
    SetTokenStatusEvent.InputTuple,
    SetTokenStatusEvent.OutputTuple,
    SetTokenStatusEvent.OutputObject
  >;
  getEvent(
    key: "UnlockPaywall"
  ): TypedContractEvent<
    UnlockPaywallEvent.InputTuple,
    UnlockPaywallEvent.OutputTuple,
    UnlockPaywallEvent.OutputObject
  >;

  filters: {
    "EffectivelyTransfer(address,address,address,uint256)": TypedContractEvent<
      EffectivelyTransferEvent.InputTuple,
      EffectivelyTransferEvent.OutputTuple,
      EffectivelyTransferEvent.OutputObject
    >;
    EffectivelyTransfer: TypedContractEvent<
      EffectivelyTransferEvent.InputTuple,
      EffectivelyTransferEvent.OutputTuple,
      EffectivelyTransferEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "SetAccountStatus(address,uint256,uint256)": TypedContractEvent<
      SetAccountStatusEvent.InputTuple,
      SetAccountStatusEvent.OutputTuple,
      SetAccountStatusEvent.OutputObject
    >;
    SetAccountStatus: TypedContractEvent<
      SetAccountStatusEvent.InputTuple,
      SetAccountStatusEvent.OutputTuple,
      SetAccountStatusEvent.OutputObject
    >;

    "SetContractStatus(uint256,uint256)": TypedContractEvent<
      SetContractStatusEvent.InputTuple,
      SetContractStatusEvent.OutputTuple,
      SetContractStatusEvent.OutputObject
    >;
    SetContractStatus: TypedContractEvent<
      SetContractStatusEvent.InputTuple,
      SetContractStatusEvent.OutputTuple,
      SetContractStatusEvent.OutputObject
    >;

    "SetHandlingFeeRatio(uint256,uint256)": TypedContractEvent<
      SetHandlingFeeRatioEvent.InputTuple,
      SetHandlingFeeRatioEvent.OutputTuple,
      SetHandlingFeeRatioEvent.OutputObject
    >;
    SetHandlingFeeRatio: TypedContractEvent<
      SetHandlingFeeRatioEvent.InputTuple,
      SetHandlingFeeRatioEvent.OutputTuple,
      SetHandlingFeeRatioEvent.OutputObject
    >;

    "SetInvoiceExpiration(uint256,uint256)": TypedContractEvent<
      SetInvoiceExpirationEvent.InputTuple,
      SetInvoiceExpirationEvent.OutputTuple,
      SetInvoiceExpirationEvent.OutputObject
    >;
    SetInvoiceExpiration: TypedContractEvent<
      SetInvoiceExpirationEvent.InputTuple,
      SetInvoiceExpirationEvent.OutputTuple,
      SetInvoiceExpirationEvent.OutputObject
    >;

    "SetRole(address,uint256,uint256)": TypedContractEvent<
      SetRoleEvent.InputTuple,
      SetRoleEvent.OutputTuple,
      SetRoleEvent.OutputObject
    >;
    SetRole: TypedContractEvent<
      SetRoleEvent.InputTuple,
      SetRoleEvent.OutputTuple,
      SetRoleEvent.OutputObject
    >;

    "SetTokenStatus(address,uint256,uint256)": TypedContractEvent<
      SetTokenStatusEvent.InputTuple,
      SetTokenStatusEvent.OutputTuple,
      SetTokenStatusEvent.OutputObject
    >;
    SetTokenStatus: TypedContractEvent<
      SetTokenStatusEvent.InputTuple,
      SetTokenStatusEvent.OutputTuple,
      SetTokenStatusEvent.OutputObject
    >;

    "UnlockPaywall(address,address,uint64,address)": TypedContractEvent<
      UnlockPaywallEvent.InputTuple,
      UnlockPaywallEvent.OutputTuple,
      UnlockPaywallEvent.OutputObject
    >;
    UnlockPaywall: TypedContractEvent<
      UnlockPaywallEvent.InputTuple,
      UnlockPaywallEvent.OutputTuple,
      UnlockPaywallEvent.OutputObject
    >;
  };
}
